catChaWeb/Models/CItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace catChaWeb.Models
{
    public class CItems
    {
        public int fPId { get; set; }
        public int fPCld { get; set; }
        public string fPName { get; set; }
        public string fPDescription { get; set; }
        public byte[] fPImage { get; set; }
        public int fRQunatity { get; set; }
        public double fLotteryP { get; set; }

    }
}

catChaWeb/Models/CItmesFactory.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace catChaWeb.Models
{
    public class CItmesFactory
    {
        //呼叫所有包含機率的物品的方法
        public CItems 計算機率道具()
        {
            catchaEntities db = new catchaEntities();
            var datas = from p in db.Game_Product_Total
                        where p.Lottery_Probability !=0
                        select p;
            return "";
        }
    }
}

catChaWeb/ViewModels/CMain.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace catChaWeb.Models
{
    public class CMain
    {
    }
}

catChaWeb/ViewModels/CRunGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace catChaWeb.Models
{
    public class CRunGame
    {
    }
}

catChaWeb/ViewModels/CSummon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace catChaWeb.Models
{
    public class CSummon
    {
    }
}

catChaWeb/Controllers/CatRunGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace catChaWeb.Controllers
{
    public class CatRunGameController : Controller
    {
        // GET: CatRunGame
        public ActionResult Index()
        {
            return View();
        }
    }
}

catChaWeb/Controllers/GameMainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace catChaWeb.Controllers
{
    public class GameMainController : Controller
    {
        // GET: GameMain
        public ActionResult Index()
        {
            return View();
        }
    }
}

catChaWeb/Controllers/GameStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace catChaWeb.Controllers
{
    public class GameStoreController : Controller
    {
        // GET: GameStore
        public ActionResult Index()
        {
            return View();
        }
    }
}

catChaWeb/Controllers/SummonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace catChaWeb.Controllers
{
    public class SummonController : Controller
    {
        // GET: Summon
        public ActionResult 所有物品()
        {
            catchaEntities db= new catchaEntities();
            var datas = from p in db.Game_Product_Total
                        where p.Lottery_Probability > 0
                        select p;
            return View(datas);
        }
    }
}

catChaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("全部物品", "所有物品", "Summon", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

catChaWeb/Views/Summon/所有物品.cshtml
@model IEnumerable<catChaWeb.Game_Product_Total>

@{
    ViewBag.Title = "所有物品";
}

<h2>所有物品</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Product_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_Category_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product_Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lottery_Probability)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product_Category_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product_Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product_Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lottery_Probability)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>